# Generated by Django 5.2.7 on 2025-10-21 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('orientacion', 'Orientación'), ('seguimiento', 'Seguimiento'), ('urgencia', 'Urgencia')], default='orientacion', max_length=30)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('telefonica', 'Telefónica')], default='presencial', max_length=30)),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)])),
                ('motivo', models.TextField(blank=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
