# Generated by Django 5.2.7 on 2025-10-21 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('psicologas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='psicologa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='psicologas.perfilpsicologa'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('psicologa', 'fecha_hora')},
        ),
    ]
