# Generated by Django 5.2.7 on 2025-10-21 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psicologas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpsicologa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_psicologa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='psicologa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='psicologas.perfilpsicologa'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('psicologa', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
    ]
